//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGPB.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OGPB.language.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Depot.
        /// </summary>
        internal static string FacilitiesAllianceDepot {
            get {
                return ResourceManager.GetString("FacilitiesAllianceDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alliance depot supplies fuel to friendly fleets in orbit helping with defense..
        /// </summary>
        internal static string FacilitiesAllianceDepotDescription {
            get {
                return ResourceManager.GetString("FacilitiesAllianceDepotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile Silo.
        /// </summary>
        internal static string FacilitiesMissileSilo {
            get {
                return ResourceManager.GetString("FacilitiesMissileSilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missile silos are used to store missiles..
        /// </summary>
        internal static string FacilitiesMissileSiloDescription {
            get {
                return ResourceManager.GetString("FacilitiesMissileSiloDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nanite Factory.
        /// </summary>
        internal static string FacilitiesNaniteFactory {
            get {
                return ResourceManager.GetString("FacilitiesNaniteFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the ultimate in robotics technology. Each level cuts the construction time for buildings, ships, and defenses..
        /// </summary>
        internal static string FacilitiesNaniteFactoryDescription {
            get {
                return ResourceManager.GetString("FacilitiesNaniteFactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Lab.
        /// </summary>
        internal static string FacilitiesResearchLab {
            get {
                return ResourceManager.GetString("FacilitiesResearchLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A research lab is required in order to conduct research into new technologies..
        /// </summary>
        internal static string FacilitiesResearchLabDescription {
            get {
                return ResourceManager.GetString("FacilitiesResearchLabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robotics Factory.
        /// </summary>
        internal static string FacilitiesRoboticsFactory {
            get {
                return ResourceManager.GetString("FacilitiesRoboticsFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robotic factories provide construction robots to aid in the construction of buildings. Each level increases the speed of the upgrade of buildings..
        /// </summary>
        internal static string FacilitiesRoboticsFactoryDescription {
            get {
                return ResourceManager.GetString("FacilitiesRoboticsFactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipyard.
        /// </summary>
        internal static string FacilitiesShipyard {
            get {
                return ResourceManager.GetString("FacilitiesShipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All types of ships and defensive facilities are built in the planetary shipyard..
        /// </summary>
        internal static string FacilitiesShipyardDescription {
            get {
                return ResourceManager.GetString("FacilitiesShipyardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terraformer.
        /// </summary>
        internal static string FacilitiesTerraformer {
            get {
                return ResourceManager.GetString("FacilitiesTerraformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The terraformer increases the usable surface of planets..
        /// </summary>
        internal static string FacilitiesTerraformerDescription {
            get {
                return ResourceManager.GetString("FacilitiesTerraformerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour Technology.
        /// </summary>
        internal static string ResearchArmour {
            get {
                return ResourceManager.GetString("ResearchArmour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special alloys improve the armour on ships and defensive structures. The effectiveness of the armour can be increased by 10 % per level..
        /// </summary>
        internal static string ResearchArmourDescription {
            get {
                return ResourceManager.GetString("ResearchArmourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astrophysics.
        /// </summary>
        internal static string ResearchAstrophysics {
            get {
                return ResourceManager.GetString("ResearchAstrophysics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With an astrophysics research module, ships can undertake long expeditions. Every second level of this technology will allow you to colonise an extra planet..
        /// </summary>
        internal static string ResearchAstrophysicsDescription {
            get {
                return ResourceManager.GetString("ResearchAstrophysicsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustion Drive.
        /// </summary>
        internal static string ResearchCombustion {
            get {
                return ResourceManager.GetString("ResearchCombustion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The development of this drive makes some ships faster, although each level increases speed by only 10 % of the base value..
        /// </summary>
        internal static string ResearchCombustionDescription {
            get {
                return ResourceManager.GetString("ResearchCombustionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Technology.
        /// </summary>
        internal static string ResearchComputer {
            get {
                return ResourceManager.GetString("ResearchComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More fleets can be commanded by increasing computer capacities. Each level of computer technology increases the maximum number of fleets by one..
        /// </summary>
        internal static string ResearchComputerDescription {
            get {
                return ResourceManager.GetString("ResearchComputerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Technology.
        /// </summary>
        internal static string ResearchEnergy {
            get {
                return ResourceManager.GetString("ResearchEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command of different types of energy is necessary for many new technologies..
        /// </summary>
        internal static string ResearchEnergyDescription {
            get {
                return ResourceManager.GetString("ResearchEnergyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espionage Technology.
        /// </summary>
        internal static string ResearchEspionage {
            get {
                return ResourceManager.GetString("ResearchEspionage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about other planets and moons can be gained using this technology..
        /// </summary>
        internal static string ResearchEspionageDescription {
            get {
                return ResourceManager.GetString("ResearchEspionageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graviton Technology.
        /// </summary>
        internal static string ResearchGraviton {
            get {
                return ResourceManager.GetString("ResearchGraviton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firing a concentrated charge of graviton particles can create an artificial gravity field, which can destroy ships or even moons..
        /// </summary>
        internal static string ResearchGravitonDescription {
            get {
                return ResourceManager.GetString("ResearchGravitonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperspace Drive.
        /// </summary>
        internal static string ResearchHyperspaceDrive {
            get {
                return ResourceManager.GetString("ResearchHyperspaceDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperspace drive warps space around a ship. The development of this drive makes some ships faster, although each level increases speed by only 30 % of the base value..
        /// </summary>
        internal static string ResearchHyperspaceDriveDescription {
            get {
                return ResourceManager.GetString("ResearchHyperspaceDriveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperspace Technology.
        /// </summary>
        internal static string ResearchHyperspaceTech {
            get {
                return ResourceManager.GetString("ResearchHyperspaceTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By integrating the 4th and 5th dimensions it is now possible to research a new kind of drive that is more economical and efficient..
        /// </summary>
        internal static string ResearchHyperspaceTechDescription {
            get {
                return ResourceManager.GetString("ResearchHyperspaceTechDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse Drive.
        /// </summary>
        internal static string ResearchImpulse {
            get {
                return ResourceManager.GetString("ResearchImpulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The impulse drive is based on the reaction principle. Further development of this drive makes some ships faster, although each level increases speed by only 20 % of the base value..
        /// </summary>
        internal static string ResearchImpulseDescription {
            get {
                return ResourceManager.GetString("ResearchImpulseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Technology.
        /// </summary>
        internal static string ResearchIon {
            get {
                return ResourceManager.GetString("ResearchIon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deadly beam of accelerated ions. This causes enormous damage when striking an object..
        /// </summary>
        internal static string ResearchIonDescription {
            get {
                return ResourceManager.GetString("ResearchIonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intergalactic Research Network.
        /// </summary>
        internal static string ResearchIRN {
            get {
                return ResourceManager.GetString("ResearchIRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researchers on different planets communicate via this network..
        /// </summary>
        internal static string ResearchIRNDescription {
            get {
                return ResourceManager.GetString("ResearchIRNDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Technology.
        /// </summary>
        internal static string ResearchLaser {
            get {
                return ResourceManager.GetString("ResearchLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focusing light produces a beam that causes damage when it strikes an object..
        /// </summary>
        internal static string ResearchLaserDescription {
            get {
                return ResourceManager.GetString("ResearchLaserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasma Technology.
        /// </summary>
        internal static string ResearchPlasma {
            get {
                return ResourceManager.GetString("ResearchPlasma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A further development of ion technology which accelerates high-energy Plasma, a result of super-heating Ions. This has a devastating effect when striking an object..
        /// </summary>
        internal static string ResearchPlasmaDescription {
            get {
                return ResourceManager.GetString("ResearchPlasmaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shielding Technology.
        /// </summary>
        internal static string ResearchShielding {
            get {
                return ResourceManager.GetString("ResearchShielding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shielding technology makes the shields on ships and defensive facilities more efficient. Each level of shield technology increases the strength of the shields by 10 % of the base value..
        /// </summary>
        internal static string ResearchShieldingDescription {
            get {
                return ResourceManager.GetString("ResearchShieldingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons Technology.
        /// </summary>
        internal static string ResearchWeapons {
            get {
                return ResourceManager.GetString("ResearchWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons technology makes weapons systems more efficient. Each level of weapons technology increases the weapon strength of units by 10 % of the base value..
        /// </summary>
        internal static string ResearchWeaponsDescription {
            get {
                return ResourceManager.GetString("ResearchWeaponsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal.
        /// </summary>
        internal static string ResourcesCrystal {
            get {
                return ResourceManager.GetString("ResourcesCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Mine.
        /// </summary>
        internal static string ResourcesCrystalMine {
            get {
                return ResourceManager.GetString("ResourcesCrystalMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystals are the main resource used to build electronic circuits and form certain alloy compounds..
        /// </summary>
        internal static string ResourcesCrystalMineDescription {
            get {
                return ResourceManager.GetString("ResourcesCrystalMineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Storage.
        /// </summary>
        internal static string ResourcesCrystalStorage {
            get {
                return ResourceManager.GetString("ResourcesCrystalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides storage for excess crystal..
        /// </summary>
        internal static string ResourcesCrystalStorageDescription {
            get {
                return ResourceManager.GetString("ResourcesCrystalStorageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuterium.
        /// </summary>
        internal static string ResourcesDeuterium {
            get {
                return ResourceManager.GetString("ResourcesDeuterium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuterium Synthesizer.
        /// </summary>
        internal static string ResourcesDeuteriumSynthesizer {
            get {
                return ResourceManager.GetString("ResourcesDeuteriumSynthesizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuterium is used as fuel for spaceships and is harvested in the deep sea. Deuterium is a rare substance and is thus relatively expensive..
        /// </summary>
        internal static string ResourcesDeuteriumSynthesizerDescription {
            get {
                return ResourceManager.GetString("ResourcesDeuteriumSynthesizerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuterium Tank.
        /// </summary>
        internal static string ResourcesDeuteriumTank {
            get {
                return ResourceManager.GetString("ResourcesDeuteriumTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giant tanks for storing newly-extracted deuterium..
        /// </summary>
        internal static string ResourcesDeuteriumTankDescription {
            get {
                return ResourceManager.GetString("ResourcesDeuteriumTankDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string ResourcesEnergy {
            get {
                return ResourceManager.GetString("ResourcesEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion Reactor.
        /// </summary>
        internal static string ResourcesFusionReactor {
            get {
                return ResourceManager.GetString("ResourcesFusionReactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fusion reactor uses deuterium to produce energy..
        /// </summary>
        internal static string ResourcesFusionReactorDescription {
            get {
                return ResourceManager.GetString("ResourcesFusionReactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        internal static string ResourcesMetal {
            get {
                return ResourceManager.GetString("ResourcesMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal Mine.
        /// </summary>
        internal static string ResourcesMetalMine {
            get {
                return ResourceManager.GetString("ResourcesMetalMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in the extraction of metal ore, metal mines are of primary importance to all emerging and established empires..
        /// </summary>
        internal static string ResourcesMetalMineDescription {
            get {
                return ResourceManager.GetString("ResourcesMetalMineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal Storage.
        /// </summary>
        internal static string ResourcesMetalStorage {
            get {
                return ResourceManager.GetString("ResourcesMetalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides storage for excess metal..
        /// </summary>
        internal static string ResourcesMetalStorageDescription {
            get {
                return ResourceManager.GetString("ResourcesMetalStorageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Hour.
        /// </summary>
        internal static string ResourcesPerHour {
            get {
                return ResourceManager.GetString("ResourcesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Plant.
        /// </summary>
        internal static string ResourcesSolarPlant {
            get {
                return ResourceManager.GetString("ResourcesSolarPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar power plants absorb energy from solar radiation. All mines need energy to operate..
        /// </summary>
        internal static string ResourcesSolarPlantDescription {
            get {
                return ResourceManager.GetString("ResourcesSolarPlantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battlecruiser.
        /// </summary>
        internal static string ShipyardBattlecruiser {
            get {
                return ResourceManager.GetString("ShipyardBattlecruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Battlecruiser is highly specialized in the interception of hostile fleets..
        /// </summary>
        internal static string ShipyardBattlecruiserDescription {
            get {
                return ResourceManager.GetString("ShipyardBattlecruiserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battleship.
        /// </summary>
        internal static string ShipyardBattleship {
            get {
                return ResourceManager.GetString("ShipyardBattleship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battleships form the backbone of a fleet. Their heavy cannons, high speed, and large cargo holds make them opponents to be taken seriously..
        /// </summary>
        internal static string ShipyardBattleshipDescription {
            get {
                return ResourceManager.GetString("ShipyardBattleshipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomber.
        /// </summary>
        internal static string ShipyardBomber {
            get {
                return ResourceManager.GetString("ShipyardBomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bomber was developed especially to destroy the planetary defenses of a world..
        /// </summary>
        internal static string ShipyardBomberDescription {
            get {
                return ResourceManager.GetString("ShipyardBomberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colony Ship.
        /// </summary>
        internal static string ShipyardColonyShip {
            get {
                return ResourceManager.GetString("ShipyardColonyShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacant planets can be colonized with this ship..
        /// </summary>
        internal static string ShipyardColonyShipDescription {
            get {
                return ResourceManager.GetString("ShipyardColonyShipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruiser.
        /// </summary>
        internal static string ShipyardCruiser {
            get {
                return ResourceManager.GetString("ShipyardCruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruisers are armoured almost three times as heavily as heavy fighters and have more than twice the firepower. In addition, they are very fast..
        /// </summary>
        internal static string ShipyardCruiserDescription {
            get {
                return ResourceManager.GetString("ShipyardCruiserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathstar.
        /// </summary>
        internal static string ShipyardDeathstar {
            get {
                return ResourceManager.GetString("ShipyardDeathstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destructive power of the deathstar is unsurpassed..
        /// </summary>
        internal static string ShipyardDeathstarDescription {
            get {
                return ResourceManager.GetString("ShipyardDeathstarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyer.
        /// </summary>
        internal static string ShipyardDestroyer {
            get {
                return ResourceManager.GetString("ShipyardDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destroyer is the king of the warships..
        /// </summary>
        internal static string ShipyardDestroyerDescription {
            get {
                return ResourceManager.GetString("ShipyardDestroyerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espionage Probe.
        /// </summary>
        internal static string ShipyardEspionageProbe {
            get {
                return ResourceManager.GetString("ShipyardEspionageProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espionage probes are small, agile drones that provide data on fleets and planets over great distances..
        /// </summary>
        internal static string ShipyardEspionageProbeDescription {
            get {
                return ResourceManager.GetString("ShipyardEspionageProbeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Fighter.
        /// </summary>
        internal static string ShipyardHeavyFighter {
            get {
                return ResourceManager.GetString("ShipyardHeavyFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This fighter is better armoured and has a higher attack strength than the light fighter..
        /// </summary>
        internal static string ShipyardHeavyFighterDescription {
            get {
                return ResourceManager.GetString("ShipyardHeavyFighterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Cargo.
        /// </summary>
        internal static string ShipyardLargeCargo {
            get {
                return ResourceManager.GetString("ShipyardLargeCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cargo ship has a much larger cargo capacity than the small cargo, and is generally faster thanks to an improved drive..
        /// </summary>
        internal static string ShipyardLargeCargoDescription {
            get {
                return ResourceManager.GetString("ShipyardLargeCargoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Fighter.
        /// </summary>
        internal static string ShipyardLightFighter {
            get {
                return ResourceManager.GetString("ShipyardLightFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first fighting ship all emperors will build. The light fighter is an agile ship, but vulnerable by themselves. In mass numbers, they can become a great threat to any empire. They are the first to accompany small and large cargo to hostile planets with minor defenses..
        /// </summary>
        internal static string ShipyardLightFighterDescription {
            get {
                return ResourceManager.GetString("ShipyardLightFighterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycler.
        /// </summary>
        internal static string ShipyardRecycler {
            get {
                return ResourceManager.GetString("ShipyardRecycler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recyclers are the only ships able to harvest debris fields floating in a planets orbit after combat..
        /// </summary>
        internal static string ShipyardRecyclerDescription {
            get {
                return ResourceManager.GetString("ShipyardRecyclerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Cargo.
        /// </summary>
        internal static string ShipyardSmallCargo {
            get {
                return ResourceManager.GetString("ShipyardSmallCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The small cargo is an agile ship which can quickly transport resources to other planets..
        /// </summary>
        internal static string ShipyardSmallCargoDescription {
            get {
                return ResourceManager.GetString("ShipyardSmallCargoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Satellite.
        /// </summary>
        internal static string ShipyardSolarSatellite {
            get {
                return ResourceManager.GetString("ShipyardSolarSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar satellites are simple platforms of solar cells, located in a high, stationary orbit. They gather sunlight and transmit it to the ground station via laser.  A solar satellite produces {DO WE WANT THIS IN OUR DESCRIPTION?} energy on this planet..
        /// </summary>
        internal static string ShipyardSolarSatelliteDescription {
            get {
                return ResourceManager.GetString("ShipyardSolarSatelliteDescription", resourceCulture);
            }
        }
    }
}
